[package]
name = "learnopengl-raytracer"
version = "0.1.0"
authors = ["Finn <mail@kawzeg.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
miniquad = "0.3.0-alpha.43"
png = "0.16.8"
bitvec = "0.21.1"
